config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/edit'
  get 'groups/show'
  get 'groups/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  devise_for :users
  end

  root to: "homes#top"
  get "home/about"=>"homes#about"



  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy, :index]
    get 'join' => "group_users#join"
    delete 'leave' => "group_users#leave"
    get 'new/mail' => "groups#new_mail"
    get 'send/mail' => "groups#send_mail"

  end

  get "search" => "searches#search"

end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 20 }

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :group_image

  def get_group_image(width,height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit, :destroy]


  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      @group_user = GroupUser.new
      @group_user.user_id = current_user.id
      @group_user.group_id = @group.id
      @group_user.save
      redirect_to groups_path
    else
      render "new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render "edit"
    end
  end

  def show
    @group = Group.find(params[:id])
    @group_users = GroupUser.where(group_id: @group)
  end

  def index
    @groups = Group.all
    @group_users = GroupUser.all
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end
  
  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    EventMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group,local:true do |f| %>
  <div class="form-group">
    <%= f.label :"グループ名" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"紹介文" %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"グループ画像" %><br>
    <%= f.file_field :group_image %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image(80,80) %></td>
        <td>
          <%= link_to group_path(group) do %>
            <%= group.name %>
          <% end %>
        </td>
        <td><%= group.introduction %></td>
        <td><%= group.users.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Create Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <dev class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </dev>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Create Group</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Event Mail</h1>
      <%= render 'layouts/errors', obj: @group %>
      <%= form_with url: group_send_mail_path(@group),method: :get do |f| %>
        <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :mail_title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Content %>
          <%= f.text_area :mail_content, class: "form-control" %>
        </div>
        <div>
          <%= f.submit "送信" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>送信が完了しました</h3>
      <div>内容は以下の通りです。</div>
      <div>
        [タイトル]<br>
        <p><%= @mail_title %></p>
      </div>
      <div>
        [本文]<br>
        <p><%= safe_join(@mail_content.split("\n"), tag(:br)) %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <dev class="col-md-8 offset-md-1">
      <h2>Group Dtail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
          </tr>
        </tbody>
        <tr>
          <td><%= image_tag @group.get_group_image(50,50) %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group_users.each do |group_user| %>
              <%= group_user.user.name %><br>
            <% end %>
          </td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to "Edit", edit_group_path(@group), class: 'btn btn-success' %>
            <% elsif @group.users.include?(current_user) %>
              <%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to "Join this group", group_join_path(@group), class: 'btn btn-success' %>
            <% end %>
          </td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to "Notice an Event", group_new_mail_path(@group), class: 'btn btn-info' %>
            <% end %>
          </td>
        </tr>
      </table>
    </dev>
  </div>
</div>