config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/edit'
  get 'groups/show'
  get 'groups/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  devise_for :users
  end

  root to: "homes#top"
  get "home/about"=>"homes#about"



  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy, :index]
    get 'join' => "group_users#join"
    delete 'leave' => "group_users#leave"
    get 'new/mail' => "groups#new_mail"
    get 'send/mail' => "groups#send_mail"

  end

  get "search" => "searches#search"

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_tag_relations, dependent: :destroy
  has_many :tags, through: :book_tag_relations

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

#Scope 設定
  scope :latest, -> {order(created_at: :desc)}
  scope :star_count, -> {order(star: :desc)}


# 検索条件分岐
  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def save_tag(sent_tags)
# タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag) unless self.tags.nil?
# 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
# 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags
# 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag: old)
    end
# 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag: new)
      self.tags << new_post_tag
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @nbook = Book.new
    @book_comment = BookComment.new
    @tag = @book.tags
  end

  def index
    @tag=Tag.all

    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    tag_list = params[:book][:tag].split(',')
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @tag_list = @book.tags.pluck(:tag).join(',')
  end

  def update
    @book = Book.find(params[:id])
    tag_list = params[:book][:tag].split(',')
    if  @book.update(book_params)
# このpost_idに紐づいていたタグを@oldに入れる
        @old_relations=BookTagRelation.where(book_id: @book.id)
# それらを取り出し、消す。消し終わる
        @old_relations.each do |relation|
          relation.delete
        end
        @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_edit_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>

    <div class="form-group" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star %>

    <div id="rate_<%= book.id %>" class="form-group"></div>


    <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
    </div>



<% end %>


    <script>
    $(document).on('turbolinks:load', function() {
        let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
        rate_<%= book.id %>.innerHTML = ""
        let option_<%= book.id %> = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: "<%= book.star %>",
            readOnly: true,
          };
        raty(raty_<%= book.id %> ,option_<%= book.id %>);
    });
    </script>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, value: @tag_list, class: 'form-control book_tag' %>
  </div>

  <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>

    <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
      let raty_elem = document.querySelector('#post_raty');
      raty_elem.innerHTML = ""
      let option = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(raty_elem,option);
      });
    </script>

  <% else %>
    <%= render "static_rate", book: book %>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book, class: "book_#{book.id}", data: {"turbolinks" => false} %></td>
        <td><%= book.body %></td>
          <td>
            <% book.tags.each do |list| %>
              <li class="list-unstyled">
            <%= link_to list.tag, search_path(tag: list.tag) %>
              </li>
            <% end %>
          </td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render 'favorites/favorite-btn', book: book %>
        </td>

        <td>
          <p>コメント数：<%= book.book_comments.count %></p>
        </td>
        <td>
          <div id="rate_<%= book.id %>"></div>
          <script>
            $(document).on('turbolinks:load', function() {
              let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
              rate_<%= book.id %>.innerHTML = ""
              let option_<%= book.id %> = {
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                readOnly: true,
                score: <%= book.star %>,
              };
              raty(raty_<%= book.id %> ,option_<%= book.id %>);
            });
          </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function() {
    let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
    rate_<%= book.id %>.innerHTML = ""
    let option_<%= book.id %> = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= book.star %>",
        readOnly: true,
      };
    raty(raty_<%= book.id %> ,option_<%= book.id %>);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book, tag_list: @tag_list %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p>
        <%= link_to '新しい順', books_path(latest: "true") %>
        |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      </p>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% @tag.each do |list| %>
              <li class="list-unstyled">
            <%= link_to list.tag, search_path(tag: list.tag) %>
              </li>
            <% end %>
          </td>
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>
          <td id="comment_counter"><p><%= render "book_comments/comments_counter", book: @book %></p></td>
          <td><%= render "static_rate", book: @book %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success", data: {"turbolinks" => false} %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <div id="book_comment">
        <%= render 'book_comments/book_comments', book: @book %>
      </div>

      <div>
        <%= form_with model: [@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment, rows:5, style: "width:100%", placeholder: "コメントをここに", class: "mt-3", value: "" %><br>
          <%= f.submit "送信する" %>
        <% end %>
      </div>

    </div>
  </div>
</div>