config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/edit'
  get 'groups/show'
  get 'groups/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  devise_for :users
  end

  root to: "homes#top"
  get "home/about"=>"homes#about"



  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups, only: [:index, :show, :edit, :new, :create, :destroy, :update] do
    resource :group_users, only: [:create, :destroy, :index]
    get 'join' => "group_users#join"
    delete 'leave' => "group_users#leave"
    get 'new/mail' => "groups#new_mail"
    get 'send/mail' => "groups#send_mail"

  end

  get "search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_tag_relations, dependent: :destroy
  has_many :tags, through: :book_tag_relations

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

#Scope 設定
  scope :latest, -> {order(created_at: :desc)}
  scope :star_count, -> {order(star: :desc)}


# 検索条件分岐
  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def save_tag(sent_tags)
# タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:tag) unless self.tags.nil?
# 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
# 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags
# 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag: old)
    end
# 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag: new)
      self.tags << new_post_tag
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/book_tag_relation.rb
class BookTagRelation < ApplicationRecord
  belongs_to :book
  belongs_to :tag
  
  validates :book_id, presence: true
  validates :tag_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :book
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 20 }

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :group_image

  def get_group_image(width,height)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

belongs_to :user
belongs_to :group

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :book_tag_relations, dependent: :destroy, foreign_key: 'tag_id'
# タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :books,through: :book_tag_relations
  
  validates :tag, uniqueness: true, presence: true
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path =Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

# 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user =User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @nbook = Book.new
    @book_comment = BookComment.new
    @tag = @book.tags
  end

  def index
    @tag=Tag.all

    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    tag_list = params[:book][:tag].split(',')
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @tag_list = @book.tags.pluck(:tag).join(',')
  end

  def update
    @book = Book.find(params[:id])
    tag_list = params[:book][:tag].split(',')
    if  @book.update(book_params)
# このpost_idに紐づいていたタグを@oldに入れる
        @old_relations=BookTagRelation.where(book_id: @book.id)
# それらを取り出し、消す。消し終わる
        @old_relations.each do |relation|
          relation.delete
        end
        @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p id="notice"><%= notice %></p>
      </div>
      <% unless current_page?(root_path) %>
        <%if user_signed_in? %>
          <div class="col-md-5">
            <div class="search_form text-right mt-2 ">
              <%= form_with url: search_path, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :range, ["User", "Book"] %>
                <%= f.select :search, [["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]] %>
                <%= f.submit "検索" %>
              <% end %>
            </div>
          </div>

          <div class="col-md-4">
            <div class="search_form text-right mt-2 ">
              <%= form_with url: search_path, method: :get do |f| %>
                <%= f.text_field :tag %>
                <%= f.submit "タグ検索" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>

      </main>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>